/*
 * App URI: access/access_test
 * Source Location: access/access_test.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5696), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("access/access_test", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * access_test.js
			 * Created at 2025. 12. 1. 오후 2:12:57.
			 *
			 * @author LCM
			 ************************************************/

			/*
			 * "Button" 버튼(btn1)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn1Click(e){
			//// GET 요청
			//fetch('/api/accessibility/audit?url=http://localhost:8080/exbuilder/view?clx=/access/test.clx')
			//  .then(response => response.json())
			//  .then(data => {
			//    console.log('검사 결과:', data);
			//    if (data.success) {
			//      console.log('결과 JSON:', data.result);
			//    }
			//  });
			//
			//// POST 요청
			//fetch('/api/accessibility/audit', {
			//  method: 'POST',
			//  headers: {
			//    'Content-Type': 'application/x-www-form-urlencoded',
			//  },
			//  body: 'url=http://localhost:8080/exbuilder/view?clx=/sample/Main.clx'
			//})
			//  .then(response => response.json())
			//  .then(data => console.log(data));
			app.lookup("sms1").send()
			}

			/*
			 * "Button" 버튼(btn2)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn2Click(e){
				var btn2 = e.control;
				app.lookup("sms2").send();
			};
			// End - User Script
			
			// Header
			var submission_1 = new cpr.protocols.Submission("sms1");
			submission_1.action = "../api/accessibility/audit.do?url=http://localhost:8080/exbuilder/view?clx=/access/test.clx";
			submission_1.mediaType = "application/json";
			submission_1.responseType = "javascript";
			app.register(submission_1);
			
			var submission_2 = new cpr.protocols.Submission("sms2");
			submission_2.method = "get";
			submission_2.action = "../api/accessibility/insights.do";
			app.register(submission_2);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button("btn1");
			button_1.value = "Button";
			if(typeof onBtn1Click == "function") {
				button_1.addEventListener("click", onBtn1Click);
			}
			container.addChild(button_1, {
				"top": "85px",
				"left": "329px",
				"width": "219px",
				"height": "95px"
			});
			
			var button_2 = new cpr.controls.Button("btn2");
			button_2.value = "Button";
			if(typeof onBtn2Click == "function") {
				button_2.addEventListener("click", onBtn2Click);
			}
			container.addChild(button_2, {
				"top": "239px",
				"left": "329px",
				"width": "219px",
				"height": "95px"
			});
		}
	});
	app.title = "access_test";
	cpr.core.Platform.INSTANCE.register(app);
})();
