/*
 * App URI: access/test
 * Source Location: access/test.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5696), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("access/test", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * test.js
			 * Created at 2025. 12. 1. 오후 2:15:02.
			 *
			 * @author LCM
			 ************************************************/;
			// End - User Script
			
			// Header
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button("btn1");
			button_1.value = "Button";
			container.addChild(button_1, {
				"top": "122px",
				"left": "628px",
				"width": "324px",
				"height": "86px"
			});
			
			var output_1 = new cpr.controls.Output();
			output_1.value = "Output";
			container.addChild(output_1, {
				"top": "113px",
				"left": "177px",
				"width": "319px",
				"height": "95px"
			});
			
			var inputBox_1 = new cpr.controls.InputBox("ipb1");
			container.addChild(inputBox_1, {
				"top": "255px",
				"left": "164px",
				"width": "363px",
				"height": "71px"
			});
			
			var image_1 = new cpr.controls.Image();
			image_1.src = "auditor/node_modules/playwright-core/lib/vite/traceViewer/playwright-logo.svg";
			container.addChild(image_1, {
				"top": "255px",
				"left": "639px",
				"width": "313px",
				"height": "109px"
			});
		}
	});
	app.title = "test";
	cpr.core.Platform.INSTANCE.register(app);
})();
